### ISSUE TITLE
Use `rhai-fs` as optional feature for `cargo generate` 

### ISSUE THREAD

**Issue by gabhijit** [cargo-generate/cargo-generate#1045]
This is a feature request and perhaps solving  #770 . Here is the use case. 

Let's say I am writing a tutorial and I want people to be able to generate scaffolding for each part of the tutorial incrementally. This is what I would like to do - 

1. `cargo generate --init` - Create a Workspace `Cargo.toml` with 'empty' (or default) members file. Also create an empty say `workspace-members.toml` file
2. Subsequently - `cargo generate` - Will add new member to this list and keep maintaining the current members in the `workspace-members.toml` file. So every new invocation would update this file. Anyone hand editing the file will probably know what they are doing. 

This way, all the updates can be rebuilt and `cargo generate` can incrementally build the work space and entire workspace can be rebuilt. 

An overview of solution:
1. Add a feature called `rhai-fs` (not present by default) 
2. If this feature is enabled update the engine as described [here](https://rhai.rs/book/lib/rhai-fs.html#load-package-into-engine).
3. If the feature is enabled also add a command line flag that takes `--save-ws-members`. That will determine whether this functionality is to be used or not. In the absence of this `workspace-members.yaml` file is not generated.
4. Additionally provide a simple `read_file` extension to `Rhai Extensions` (should solve #770). 

If this makes sense, I can take a shot and submit a PR for this.

**Comment by sassman** [comment]
Hi @gabhijit,

Thanks for your suggestion. In order to enable me to fully understand how this is meant to work could you elaborate on your provided example a bit further?

Things that I don't understand is:

1. cargo-generate right now operates on a provided repository that holds either a full project or several sub folders that can be used separately from another to generate scaffolding. How exactly would `cargo generate --init` work with the provided repository together
  1. What file would it pick and generate?
  2. How would the template repository be looking like?
2. Subsequently calls of cargo generate would then pick what files? How should it know what are the next files from the template repository to pick?

Also it would help me to show me maybe and example template repository as you imagine it and reference in your comment for every step what file it would pick from there and how it would process their content then.

This would allow to layout more precise a path of:

- from template repository A
- with the logic B
- we would get generated C
- and so on

**Comment by gabhijit** [comment]
@sassman : When I think about it, the solution I proposed is just complicated and even wrong.

However what I believe still is - an optional feature like `rhai-fs` would allow one to keep some 'state' in the generated project and that state can be read (possibly into some variables) and updated upon subsequent invocations of `cargo generate` on the same project. 

Something along the lines of one template to create the project for the first time and another (set of) template(s) to update the project subsequently (like say adding workspace items). This is actually a bit more involved than I thought initially, but surely will be useful. 

Let me see if I can hack something in my local repo and submit a PR to give an idea of what I have in mind.

**Comment by gabhijit** [comment]
Closing this issue as the original request doesn't seem to make much sense for the use-case described. Someone can open another issue if the `rhai-fs` feature is deemed useful.
