### ISSUE TITLE
handle projects that contain other templating languages

### ISSUE THREAD

**Issue by rahul-thakoor** [cargo-generate/cargo-generate#14]
Hello! 
I am trying to make a template for creating mdbooks. `cargo-generate` currently analyses the `Cargo.toml` file and then tries to replace the placeholders. It would be great to have mdbook templates, however, the `book.toml` file should be parsed instead. Having a `--book` flag could direct `cargo-generate` to parse `book.toml`. Any suggestions?

**Comment by epage** [comment]
From my quick glance at the code, it seems to do template replacements on all files, not just Cargo.toml.  In theory a `book.toml` would also work.

**Comment by rahul-thakoor** [comment]
hey there! Thanks @epage and @killercup.

So, I created a template here: https://github.com/rahul-thakoor/mdbook-template
Then:
`cargo-generate --git https://github.com/rahul-thakoor/mdbook-template.git`
I get the following error:

```session
🤷  Project Name: cg-md-template
🔧   Creating project called `cg-md-template`...
error: liquid: Invalid identifier
  with:
    identifier={
```

**Comment by killercup** [comment]
Oh, that's a pretty bad error message!

I _think_ it fails because one the files in your repo a handlebars template – which uses the same syntax as liquid! So, we try to evaluate it…

I'm considering if we should only try to substitute values in files that end with `.template` (or `.tpl`) or something?

**Comment by epage** [comment]
RE error message

We should probably chain in what file it failed on.  Anything else to improve the error messages?

RE Marking templates

Extensions are one option (`file.ext.liquid` is another option).  Another option is for when we add support for a configuration file, we could have a gitignore pattern for what files are templates or not.

**Comment by ashleygwilliams** [comment]
@rahul-thakoor we just landed a feature for ignoring files, `.genignore`. while not the most elegant solution to this issue, i think this may solve your problem for the moment- let me know?

**Comment by rahul-thakoor** [comment]
hey @ashleygwilliams thanks for the input. I tested the template with a `.genignore` file however im still getting the same error. 
https://github.com/rahul-thakoor/mdbook-template/blob/f2061d5ea87f2687e3fe1277670ede9dd8187f37/.genignore#L1-L3

Besides, it seems like files listed within `.genignore` will be _**cleaned up**_! However, this is not ideal since the conflicting files are necessary for `mdbook` to properly generate the book.

**Comment by ashleygwilliams** [comment]
@rahul-thakoor you are definitely right- sorry about that, i think we'll need to consider some sort of allow/ignore list for when we do the substitution. i'll look into this for a future release

**Comment by ssokolow** [comment]
At the moment, this is preventing me from using cargo-generate in the upcoming rework of my [rust-cli-boilerplate](https://github.com/ssokolow/rust-cli-boilerplate) because I use Just for build automation and Just uses Django/Jinja/Liquid/Twig-style placeholders for variable substitution.

I don't have time to learn my way around somebody else's project and then concoct a generally applicable solution right now, so I used cargo-generate placeholder names and then spent maybe 15 minutes whipping up this temporary `apply.sh` surrogate to distribute within the repo:

```sh
#!/bin/sh

if [ $# -lt 1 ]; then
    echo "Usage: $0 <path to new project directory> [...]"
    exit 1
fi

SELF_PATH="$(readlink -f "$0")"

SRC_PATH="$(dirname "$SELF_PATH")"
SELF_NAME="$(basename "$SELF_PATH")"

AUTHORS="$(git config --get user.name)  <$(git config --get user.email)>"

for target in "$@"; do (
    git clone -q -- "$SRC_PATH" "$target"

    cd -- "$target"
    rm -- "$SELF_NAME"

    if [ -e .genignore ]; then
        sed 's@\(^/\|\.\./\?\)@@g' .genignore | xargs rm --
        rm .genignore
    fi

    sed -i "s@{{\s*authors\s*}}@${AUTHORS}@" Cargo.toml
    sed -i "s@{{\s*project-name\s*}}@$(basename -- "$target")@" Cargo.toml
    find . -iname '*.rs' -exec sed -i "s@{{\s*authors\s*}}@${AUTHORS}@" {} \;
    find . -iname '*.rs' -exec sed -i "s@{{\s*\"now\"\s*|\s*date:\s*\"%Y\"\s*}}@$(date +%Y )@" {} \;

    rm -rf .git
    git init -q &&
    git add . &&
    git commit -qm "Created new project from template" &&
    echo "Created new project at $target"
); done
```

In case anyone's wondering, parentheses in Bourne shell script request a subshell, which is how the RAII-esque undoing of the `cd` after each iteration is accomplished.

**Comment by RotationMatrix** [comment]
Seems #174 might have solved this. Modifying rahul-thakoor/mdbook-template to use `cargo-generate.toml` fixed the substitution errors on my end! :tada:

Updated template: https://github.com/RotationMatrix/mdbook-template

**Comment by MarcoIeni** [comment]
This issue can be closed I think.

**Comment by taurr** [comment]
@sassman Issue can be closed - workaround for issue exists as part of our configuration, and template author can/has fixed it in their templates.
