### ISSUE TITLE
Custom variables.

### ISSUE THREAD

**Issue by epage** [cargo-generate/cargo-generate#17]
For my  python projects, I've found cookiecutter's custom variables really helpful.  I'm assuming it would be the same for `cargo-generate` (including unexpected cases like #14).

Ideas from cookiecutter
- variables are an ordered set of keys/values. 
  - Keys are variable names
  - Values are defaults.  The values are [templates that are rendered using all the previous values](https://cookiecutter.readthedocs.io/en/latest/advanced/templates_in_context.html).
  - Variables can also be [choices](https://cookiecutter.readthedocs.io/en/latest/advanced/choice_variables.html)
- Users can [globally configure variables](https://cookiecutter.readthedocs.io/en/latest/advanced/user_config.html), removing the need to be prompted for them.
- [User input is cached off for replay](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html)
  - I've not needed this as much but its useful for template debugging.

I'm also assuming that environment-derived variables (author) would still be gathered but built-in policy like "name" would not be.
- In place of this, there could be an option for variables to be set on the commandline (`cargo generate --variable name some-crate`).
- For built-in magic like case changing, can be provided as liquid filters to the template author. 
- Unsure of a good way to handle ident verification.

**Comment by theduke** [comment]
As posted on Reddit, my suggestion for variables:

`cargo-generate.toml ` in stand-alone repos and possibly in Cargo.toml for crates that are templates or crates that contain templates.
```toml
variables = [
  { type = "bool", name = "use_serde", prompt = "Add serde support?", default = true },
  { type = "choice", name = "db_type", prompt = "Which database would you like to use?", options = [ "mysql", "sqlite", "postgres"] },
 ...
]
```

`lib.rs`
```
{% if use_serde %} ... {% else %} ... {% endif %}

{% if db_type = "mysql% } .....
```

**Comment by japaric** [comment]
This is a use case from the embedded WG. I'm filling it here since it's related to the requested feature but feel free to move into its own issue if that makes sense.

To use the [cortex-m-quickstart] "template" we have the user `cargo-clone` the crate and then fill in some values manually. This last part is easy to get wrong so we have an extensive [troubleshooting] section to help the user fix things if they entered a wrong value. It would be great to turn this template into a cargo-generate template and have cargo-template request and validate user input when creating the template; that way we wouldn't need such a long troubleshooting guide!

[cortex-m-quickstart]: https://docs.rs/cortex-m-quickstart/0.3.1/cortex_m_quickstart/
[troubleshooting]: https://docs.rs/cortex-m-quickstart/0.3.1/cortex_m_quickstart/#troubleshootin

To port the template to cargo-generate we would need support for custom variables and validation. Being able to use custom logic when prompting the user would let us provide a more user friendly interface. For example:

This gets the job done:

> CG: Select your target: thumbv6m-none-eabi, thumbv7m-none-eabi, thumbv7em-none-eabi, thumbv7em-none-eabihf
> U: thumbv7em-none-eabihf

But the user would have to look up in which of these groups their device fits in. On the other hand if we could ask the user questions like this:

> CG: Your device has a cortex-m0, cortex-m3, cortex-m4, or cortex-m7 processor? (default: cortex-m3)
> U: cortex-m4
>
> CG: Does your device have a Floating Point Unit (FPU)? yes, or no? (default: no)
> U: yes

(Here we select `thumbv7em-none-eabihf`. If the user picked `cortex-m3` in the first question we don't ask about the FPU (Cortex-M3 never has an FPU))

It would be easier for them to get the target right.

The other bit of input we require is the origin and length of 2 memory blocks. Here we would request the user to enter a `u32` value for the origin and another `u32` value for the length of each memory block. The validation will consist of checking that the two memory blocks don't overlap and that they don't wrap around the address space.

> CG: Enter the location of Flash memory (default: 0x00000000)
> CG: NOTE: On STM32 devices Flash starts at 0x08000000
> U: *enter*

> CG: Enter the size of Flash memory (default: 8K)
> CG: NOTE: K = 1024 bytes
> U: 32K

I believe some build script like mechanism (`template.rs`) that lets the author script these questions and outputs some JSON with the template values would be the most flexible solution but I would be fine with any other solution that lets me implement something like this.

**Comment by sassman** [comment]
I would like to suggest a slightly different format of the `cargo-generate.toml` (as mentioned by @theduke)
The proposal is to have a dedicated section for variables and have it named placeholders (to be a bit more precise what sort of variables they are)

```toml
[placeholders]
```

Then the default variable often is going to be a simple string, for example someone may have a `summary` placeholder for their project meaning that they might use in the `README.md` and in a `cli.rs`. So this would look then like this:

```toml
[placeholders]
summary = "My awesome project that can do X and Y"
```

The other use case as described above, that supports toggles as booleans, might then look like this:

```toml
[placeholders]
use_serde = { type = "bool", prompt = "Add serde support?", default = true }
db_type = { type = "choice", prompt = "Which database would you like to use?", choices = [ "mysql", "sqlite", "postgres"] }
```

## Summed up
So essentially the placeholder name is for the users always on the left side of the equation, and the most trivial case is the most common (the simple string)
Then we have the extended format with the following attributes:
- `type` should be a list of primitive types we need to define `bool`, `string`, `choice` might be good starting points
- `prompt` could be omitted, means no interactive asking for entering, but if present it must be a string, that is presented to the user on generation
- `default` needs to be typed like `type`
- `choices` is a list of strings that are presented to choose for the user

**Comment by pedrohjordao** [comment]
I'm thinking about allocating some time to implement a proof of concept for it since I believe it is a very important functionality for the project. 
It doesn't see too complicated, any sharp edges I should expect?

**Comment by pedrohjordao** [comment]
I'm slowly going through an implementation, but I want to get the ball rolling before adding any further complexity. @sassman I will be following your scheme since it is the one that looks the cleanest for me. I'm just not 100% sure what is the point of the  `type` attribute? For now I'm only handling `string`s since it seems to be the easiest option.

**Comment by sassman** [comment]
I think the major benefit of having a `type` property there is that one can handle things different, for example a boolean type can be then used in a template as a simple `if` `else` case as it was pointed out by @theduke 

for example 

```
{% if use_serde %} ... {% else %} ... {% endif %}
```

whereas a `type = "string"` would be used slightly different:

```
{% if db_type = "mysql" % }
...
{% endif %}
```

But those things are details and can be enriched later. I guess the `type = "string"` case as an invisible default that can be omitted in the configuration covers the most needs of users, since everybody just needs to write a little more verbose template expression in order to use `if / else` semantics.

So I'd give it a shot. 🚀

**Comment by pedrohjordao** [comment]
Cool, I see your point... 
I don't think it should be too hard to extend what I'm doing to add it... I'm going to try it out over the weekend.

**Comment by pedrohjordao** [comment]
Just a quick update: I'm mostly done with it, I just need to write some tests
Hopefully I'll be able to open a PR this weekend

**Comment by sassman** [comment]
> Just a quick update: I'm mostly done with it, I just need to write some tests
> 
> Hopefully I'll be able to open a PR this weekend

Great to hear, cool stuff!

If you want (no suggestion just an offer) you can open a draft PR in the meantime and get some early feedback.

**Comment by pedrohjordao** [comment]
There you go!

**Comment by sassman** [comment]
Major pieces of this landed with [pr/275](https://github.com/cargo-generate/cargo-generate/pull/275)

I see only one missing thing compared to the original feature request above, that is user global custom variables (right now only template specific custom variables are supported).

**Comment by taurr** [comment]
Also missing as pr. the user store from th embedded WG: custom validation rules.
If the user selects specific options, later possible options may be affected.

**Comment by taurr** [comment]
Oh, and types - especially booleans - then this one would probably also solve #230
