### ISSUE TITLE
Do not attempt template substitution on files that cannot be parsed by liquid

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cargo-generate/cargo-generate#204]
liquid fails to parse some files and if that's the case, cargo-generate shouldn't try to look for template strings.

**Comment by Michael-F-Bryan** [comment]
I believe I'm hitting this problem as well.

I created a GitHub actions workflow [which uses the `${{ matrix.rust }}` variable](https://github.com/Michael-F-Bryan/github-template/blob/a539cbda6ced953ff1698cd693e4d6b6237988f5/.github/workflows/main.yml#L21) to figure out which version or `rustc` to use. This is [how you are meant to use variables with GitHub Actions](https://help.github.com/en/actions/reference/contexts-and-expression-syntax-for-github-actions#about-context-and-expressions), but my problem is `cargo generate` will try to interpolate the `matrix` variable and fail because it doesn't exist.

```console
$ cargo generate --version
cargo-generate 0.5.0
$ cargo generate --git https://github.com/Michael-F-Bryan/github-template --name ethercat
 Creating project called `ethercat`...
Error:  Error replacing placeholders `/home/michael/Documents/ethercat/.github/workflows/main.yml`
Info: caused by liquid: Unknown variable
  with:
    requested variable=matrix
    available variables=authors, crate_name, project-name
```

In the meantime, can you think of any workarounds I could use? In the long term I think the best solution would be to put a config file in the template's repo which tells `cargo-generate` which files to exclude from interpolation. Thoughts?

**Comment by MarcoIeni** [comment]
Actually you may have GitHub actions which has template variables like `{{project-name}}` inside.

Isn't it possible to ignore unknown variables like `${{ matrix.rust }}` and substitute only the known ones like `{{project-name}}`?

**Comment by sassman** [comment]
Unfortunately the used template engine liquid does not have a functionality to gracefully render only provided variables and just ignore unprovided ones.

**Comment by MarcoIeni** [comment]
> Isn't it possible to ignore unknown variables like `${{ matrix.rust }}` and substitute only the known ones like `{{project-name}}`?

I found out how to do it. 

Basically, in order to escape a liquid variable you have to substitute `{{ unknown.variable }}` with `{{ "{{ unknown.variable " }}}}`

See an example [here](https://github.com/rust-github/template/blob/master/.github/workflows/cd.yml).

**Comment by sassman** [comment]
You can at anytime use the `raw` tag to disable tag processing inside.
See the docs [here](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#raw).

**Comment by MarcoIeni** [comment]
I tried to do that with [this](https://github.com/rust-github/template/blob/0b8bf865d7cfce13bc06852ad106bfe0a6c1a140/.github/workflows/cd.yml) version of the file but it gives me the following error:
```
 Project Name: eqqw
 Creating project called `eqqw`...
Error: liquid:  --> 8:4
  |
8 | {% raw %}␊
  |    ^-^
  |
  = Unknown tag.
  with:
    requested=raw
    available tags=
    available blocks=
```

**Comment by sassman** [comment]
I guess you can give it a try with the master branch, the latest officially release does not yet contain the changes for this.
