### ISSUE TITLE
Template for library projects

### ISSUE THREAD

**Issue by vbrandl** [cargo-generate/cargo-generate#262]
It would be cool to have a possibility to create library projects using the template, so just like with `cargo new --lib` one could call `cargo generate --git https://github.com/rust-github/template.git --lib`

To do this, some kind of conditional branching would be required in the templating mechanism to

- enable publishing binaries on the GitHub release page only for binary projects
- Add `Cargo.lock` to `.gitignore` for libraries

**Comment by taurr** [comment]
I honestly don't see the issue here?
I've been using cargo-generate to create library projects regularly, but obviously the template must be designed for it.

Only issue I've had in doing so was the annoying little detail that cargo-generate insisted on initializing the folder it creates as a git repository, even though I was generating within an already existing repo - that however  will be fixed if #290 is merged.

**Comment by vbrandl** [comment]
Sure you can use different templates for binary and library projects. The motivation behind my proposal was to have a single template for both binary and library projects.

I just thought it might be cool to have a similar UX as `cargo new`. If this is a non-goal for the project, this issue can be closed, but I think some users might appreciate this feature.

**Comment by sassman** [comment]
> I just thought it might be intuitive to newcomers to mimic the behavior of cargo new. If this is a non-goal for the project, this issue can be closed, but I think some users might appreciate this feature.

I believe that is very valuable. 
The only thing where I'm not certain is how to approach that. Because in fact the template itself must support that dual-behaviour. If the template does not support it, there is nothing that cargo-generate can do about it.

So one thing we could do here is that when a user calls cargo-generate with `--lib` like
```sh
cargo generate rust-github/template.git --lib
```
some pre-populated variables will made available to the template processor, so that the author of the template can implement some `if / else` checks in order to be have as a binary template or as a library template. 

for example the `Cargo.toml` of a template might look like this:

```toml
[package]
# the usual stuff

[dependencies]
{% if crate_type == "binary" %}
structopt = "0.3.21"
{% endif %}

{% if crate_type == "binary" %}
[[bin]]
path = "src/main.rs"
name = "{{crate_name}}-cli"
{% endif %}
```

> Note: that there is the template language liquid incorporated into the `Cargo.toml`

So as you can see, if the author of the template is not prepared for this, cargo-generate cannot do much. Maybe even worst, the user would expect the `--lib` behaviour of `cargo new` but the template might look the same. 
I'm pretty sure that would confuse some people pretty hard. 

However, I think we can prepare for such a convention in any case.

**Comment by taurr** [comment]
This part...

> So as you can see, if the author of the template is not prepared for this, cargo-generate cannot do much. Maybe even worst, the user would expect the `--lib` behaviour of `cargo new` but the template might look the same.
> I'm pretty sure that would confuse some people pretty hard.

is just baad...

Honestly, in order for this feature to be useful, there must be a way to get predictive behavior - otherwise it'll just end up being more confusing than it's worth.

I do see the benefit though.

## Suggestion:

Expand the `template` section of `cargo-generate.toml`. E.g.:

```toml
[template]
types = ["lib", "bin"]
default_type = "lib"
```

Then utilize that information in order to inform the user whether the template supports the specified type or not.

This way `cargo-generate` knows what the template supports and can actually help the user. Cases where the template only supports 1 type (or even none at all!) are easy to handle be showing nice information to the user.

**Comment by sassman** [comment]
> Expand the template section of cargo-generate.toml. E.g.:

I think that won't be necessary, since on master we have meanwhile a feature for custom placeholders, that a user can define, that is documented [here](https://github.com/cargo-generate/cargo-generate/blob/master/src/lib.rs#L30) that can be totally reused for this. 

Essentially as you say, if a variable (with a naming convention) is present we can offer it, if absent we cannot. The type of this variable would be choice.

I will give it some more thought.

**Comment by taurr** [comment]
@sassman 
Yep, just saw it too - it's nice, especially that it supports `bool` from start - that way it solves a lot of issues I guess.

Only issue with using #17 for this, is the lack of support for `--lib` or `--bin` that is natural for most `cargo` users. IMHO I feel this would provide a more intuitive experience for choosing between lib and bin.

But you are right; #17 can simulate this.

**Comment by sassman** [comment]
> Only issue with using #17 for this, is the lack of support for --lib or --bin that is natural for most cargo users. IMHO I feel this would provide a more intuitive experience for choosing between lib and bin.

What would be possible is to provide with `--lib` or `--bin` a sort of shortcut to initialize the variable (instead of asking for it in a dialog mode), so the author of the template must still declare this choice variable, but the users using the template would be able to avoid the interactive dialog by providing the `--lib` or `--bin` that in fact would be just initialize the `crate_type` variable with `'bin'` or `'lib'`.

**Comment by taurr** [comment]
But in case `--lib` is specified but not defined as part of any choice variable - then what?

Do we then show an error as the user specified a flag that wasn't defined (supported)?
What about other flags? Do we only support `lib` and `bin` this way? Why?

Again; I can see #17 solve this one, I'm just not sure it is *the* solution.

**Comment by sassman** [comment]
> But in case --lib is specified but not defined as part of any choice variable - then what?

Presenting the user a warning along the lines that this given template does not support the crate type library or crate type binary, that he needs to verify the result himself. Maybe also pointing out that he needs to contact the template owner for further questions.

 > What about other flags? Do we only support lib and bin this way? Why?

For now, I'd say yes. No other shortcuts only those.

Probably it's as close as possible we can get to a practical solution. This can be also pretty good documented and an example can be provided.
