### ISSUE TITLE
Docker image with cargo-generate

### ISSUE THREAD

**Issue by morenol** [cargo-generate/cargo-generate#370]
What do you think about offering an official docker image with cargo generate installed?

Other rust projects offer an official docker image for their CLI, for instance:

https://github.com/xd009642/tarpaulin/blob/develop/Dockerfile

This could be useful for multi stage docker builds that uses cargo-generate

I can work on adding that to this repo if you think that it is ok

**Comment by sassman** [comment]
That is an interesting idea. The example with tarpaulin is maybe not the best one, because there a docker image makes a lot of sense since tarpaulin cannot run on windows or mac, hence people would probably rely on the docker on the unsupported platforms. 

For cargo-generate I'm not sure if that is really needed, since it runs on all platforms without any feature restrictions. 

But since you mentioning the multi stage docker build, do you start with a blanked project created by cargo-generate and then add the sources later on? (sounds really interesting)

**Comment by taurr** [comment]
@sassman Could you please have a look at my example repo: https://github.com/taurr/cargo-generate-action

If we have a docker hub account for this repo, we could add the needed files here, and thus have an official github action for expanding templates.

This will help testing templates a lot, as one can just expand the template(s) and build/test the output in a workflow.

Of course there's always the possibility of just promoting my repo, but I'd like the action to live in this account :-/

**Comment by sassman** [comment]
I like the idea a lot, the other day I thought also about better template testability but I did not think of an GH Action to simplify the process. 

I'll set the things up and prepare a repo here. Do you want to PR the thing over or should I just clone+push it and naming you as the author?

**Comment by taurr** [comment]
Stuff needs to be changed a little in the process - my repo here was basically a proof of concept.

If we're doing it the PR way (can we actually, considering there's no relationship between the repos?), you would have to do changes anyway as I can't setup e.g. the dockerhub token secret.

I suspect that you just cloning/stealing is the easiest. Note: the example I put in the readme is actually from a working example (private repo), and my code do mention the `--define`feature which is still outstanding :-/

**Comment by sassman** [comment]
I'm already on a refactor journey. Docker hub account is in place and things will come a long.

**Comment by taurr** [comment]
> I'm already on a refactor journey. Docker hub account is in place and things will come a long.

@sassman Could we get a status update please?

**Comment by sassman** [comment]
so the docker hub account is ready, see https://hub.docker.com/search?q=cargogenerate&type=image

However, one thing that I was thinking a bit is that the cargo-generate command for the GH action would have to take quite some assumptions and is pretty specific for the GH Actions use case.

As a user a run of cargo-generate would probably need a few less / different assumptions, so that a user can handover the parameters as close to natural as possible in comparison to the docs. 

I did not yet found a nice way to combine the 2, especially to have the GH Action reusing the more general image.

**Comment by sassman** [comment]
I hope I can prepare a little PR soon, then we can continue the discussion on code, which might help to clarify things a bit

**Comment by sassman** [comment]
so I created an own repo for the GH Action at [cargo-generate-action](https://github.com/cargo-generate/cargo-generate-action)

**Comment by taurr** [comment]
> However, one thing that I was thinking a bit is that the cargo-generate command for the GH action would have to take quite some assumptions and is pretty specific for the GH Actions use case.
> 
> As a user a run of cargo-generate would probably need a few less / different assumptions, so that a user can handover the parameters as close to natural as possible in comparison to the docs.
> 
> I did not yet found a nice way to combine the 2, especially to have the GH Action reusing the more general image.

If you really want to combine them, it'll have to be done through the `entrypoint.sh`

However, In my point of view, the main issue here is to provide the GH action so we can start testing the templates. Use of `cargo-generate` via docker is IMHO not important as `cargo-generate` is cross platform from the get-go. I really don't understand why anyone would want to use docker for executing it locally (other than because they don't want to install rust in order to compile it - but why don't we just supply with pre-compiled binaries for select platforms?)

**Comment by sassman** [comment]
first version [is out](https://github.com/marketplace/actions/cargo-generate)
