### ISSUE TITLE
Suggestion: Cancel the need for PRs to maintain `TEMPLATES.md`

### ISSUE THREAD

**Issue by MeirKriheli** [cargo-generate/cargo-generate#405]
As the number of templates grows, it'll get harder to maintain `TEMPLATES.md`.

Instead, templates should tag them self as `cargo-generate` topic or something similar, negating needed PRs for new templates.

Have  README link to that topic for available templates. See  [cookiecutter](https://github.com/topics/cookiecutter) for example, and [Classifying your repository with topics](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/classifying-your-repository-with-topics).

**Comment by sassman** [comment]
I like the idea. It's yet another convenience mechanism to discover template and make template contributions simple.

For now I'd like to keep the TEMPLATES.md to not loose those templates but would clearly encourage people to use the topics approach.

**Comment by taurr** [comment]
Then lets do a small write about it in the README.md. @MeirKriheli are you up for a little PR?

It's been a while since we featured in [This week in Rust](https://this-week-in-rust.org).... It'd be nice if we had a blogger amongst us as the amount of new stuff getting into `cargo-generate` is quite substantial. Then we should be features again, just to show there's traction.

**Comment by MeirKriheli** [comment]
@sassman you're fast, was planning to on the PR tonight :-)

**Comment by sassman** [comment]
@MeirKriheli ypu can still contribute with review and improvement suggestions :)
