### ISSUE TITLE
`cargo test` shortcut for template authors

### ISSUE THREAD

**Issue by sassman** [cargo-generate/cargo-generate#455]
As a **template author**
I want to **have an easy way to test my template code**
So that **I save time to manually generate a project, run then cargo test in it and delete the generated project again**

I imagine something like
```sh
cd my-wonderful-template
cargo generate --test

## will run cargo generate as a template user would do, but just into a temp folder
## maybe with default variables to not run interactively?
## will run cargo test in the final generated project
## will delete the temp folder
```

**Comment by taurr** [comment]
@sassman: I've got a prototype for this one running now.

It runs `cargo test --all-features -- --nocapture` instead of creating the files in the current folder as it normally would - thus running the test inside a tmp folder that is deleted upon exit.

This works very nicely, except for one caveat; I can see myself wanting to specify different arguments to `cargo test`, such as `--bins` or similar. Any ideas as to how we could specify this?

example run from my windows VM:
```shell
> cargo run -- gen --git https://github.com/Ureakim/rust-template_basic --name myproject --test
    Blocking waiting for file lock on build directory
   Compiling cargo-generate v0.10.0 (C:\Users\johnn\Desktop\Projects\cargo-generate)
    Finished dev [unoptimized + debuginfo] target(s) in 7.33s
     Running `target\debug\cargo-generate.exe gen --git https://github.com/Ureakim/rust-template_basic --name myproject --test`
 Generating template ...
[1/4]   Done: Cargo.toml  
[2/4]   Done: rustfmt.toml
[3/4]   Done: src\main.rs 
[4/4]   Done: src
   Compiling myproject v0.1.0 (C:\Users\johnn\AppData\Local\Temp\.tmpQFeb3Y)
    Finished test [unoptimized + debuginfo] target(s) in 0.95s
     Running unittests (target\debug\deps\myproject-6548a729dd0db5ee.exe)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

> 
```

**Comment by sassman** [comment]
that is also on interesting idea.
My proposal was more focussed on the idea, that you got a template in your `CWD` and you want to test this.

```sh
cargo generate test
```

or even with 
```sh
cargo generate test --all-features -- --nocapture
```

so that it would does also template the current template into a temp dir, runs just the subcommand as provided (`cargo test` or `cargo test --all-features -- --nocapture`) and removes the tmp dir afterwards.

**Comment by taurr** [comment]
I kinda like the idea about making `test` a sub-command - that way it'll be possible to give it its own range of options, even going so far as to direct them all to the actual `cargo test` command... nice 😄 

However, I don't think it'll play so nice with the other options as they haven't been created with sub-commands in thought. I know from when I did the `--list-favorites` - at the time I wanted it to be a sub-command too (as all other options are irrellevant when using it), but had to stop because in order to do so I basically had to make a subcommand for the default generate behavior...

Any idea how to setup `structopt`/`clap` to allow for this?

**Comment by taurr** [comment]
@sassman 
Been looking at this for a while now...

Unfortunately, as we allow to specify path/repo and subfolder/branch to be specified without a flag or subcommand, there is no way of adding `test` as a straight subcommand without breaking something else ☹️ 

IMHO, either we break the current CLI by introducing an interface that uses subcommands, or we need to go with `--test`. The latter is what we did with the `--list-favorites` which suffered the same problem.
