### ISSUE TITLE
remove libgit2 in favor of shelling out to git

### ISSUE THREAD

**Issue by anirudhb** [cargo-generate/cargo-generate#67]
This would remove the dependency on Git, and we would just link in libgit2. It would require less things to be installed, especially when you start distributing this as a binary, since Rust statically links everything!

**Comment by killercup** [comment]
I think we are already using the git2 crate for everything in the main
binary, and it is a binding to libgit2

**Comment by anirudhb** [comment]
Then I think your README is wrong :) See the dependency on `git`?

**Comment by killercup** [comment]
It was added in #45. I'll look into it. For running the tests, the git CLI is required.

**Comment by killercup** [comment]
@migerh, can you help me out here? In #45 you added that git is a requirement to building this crate. Was this because you wanted to run the tests, too, or does some other dependency require the git binary to exist?

If it's only because of the tests, I think this issue can be closed. Would you agree, @anirudhb?

**Comment by migerh** [comment]
I was just collecting everything needed to compile cargo-generate and did not run any tests. But I also did not aim for a minimal list of dependencies. The minimal dependencies to build `libssh2-sys` on a vanilla `ubuntu:latest` docker  image are `cmake` and `zlib1g-dev`. Instead of describing how to install `zlib1g-dev` for macOs, Windows and various Linux distros I opted to link to the git install manual, because git apparently brings this already along (at least for ubuntu).

So no, the git binary is not required to build this crate.

**Comment by migerh** [comment]
I only just now realized that I read lib**ssh2**-sys as lib**git2**-sys all this time 🤦‍♂️ Installing git just to get libssh2-sys to compile does not really make that much sense.

So I dug a little deeper. Turns out that the [git2](https://crates.io/crates/git2) crate brings libgit2 along and there's no need to install it on your system for git2 to compile:

> The source for libgit2 is included in the libgit2-sys crate so there's no need to pre-install the libgit2 library, the libgit2-sys crate will figure that and/or build that for you.

libgit2 apparently uses cmake to compile...

This raises the question why libssh2-sys can't just do the same? If that crate could bring zlib1g-dev along with it there were no need to mention it in the readme. Btw, there's also a [libz crate](https://crates.io/crates/libz-sys).

**Comment by Freaky** [comment]
For what it's worth, I'd much rather a tool just call out to git if it's only doing simple stuff.

git2 adds 20 dependencies and well over a minute to build time, not to mention adding a lot more points of failure (libssh2-rs won't even build for me unless I manually set `LIBSSH2_SYS_USE_PKG_CONFIG=1`, which isn't default because it can cause other problems).

**Comment by ashleygwilliams** [comment]
after trying this out in several workshops, i think we should remove the libgit2 dependency in favor of shelling out to git

**Comment by sassman** [comment]
I'm not really convinced that this proposal of shelling out to git will not bring a big bag of just other issues, especially multi platform issues. 

Hence I'm not in favor of going down that route. 
The recent efforts at [gitoxide](https://github.com/Byron/gitoxide) are looking very promising, so at some point we should just pick and choose and take the features from gitoxide instead of libgit.
