### ISSUE TITLE
Git default branch is not honored when using --path

### ISSUE THREAD

**Issue by chevdor** [cargo-generate/cargo-generate#704]
Here is [my template](https://github.com/chevdor/cargo-templates.git) in case this is relevant.

## The good case
using `cargo-generate` with the --git flag works fine:
```
cargo generate --destination /tmp --git https://github.com/chevdor/cargo-templates.git cli
```
and the git repo defaults to `master` as setup on my system.

## The bad case
```
cargo generate --path /path/to/cli --destination /tmp/ 
```
however generates a repo where the default branch is `main` instead of `master`.

**Comment by taurr** [comment]
This is currently by design!

When using `--path`, `cargo-generate` doesn't look for or expect anything related to git from the template folder - the user has specified the source as a plain folder after all.

To work around this, just use `--git <path to repo>` instead.

Of course that may lead you to other discoveries, as the template repo may be dirty, and `cargo-generate` will now use a checkout of it, which will not include dirty files.

**Comment by chevdor** [comment]
But I am not talking at all about anything remote.
The default branch setting is local to my system, I would expect that, even using `--path`, if a repo is initialized, the local system's config is honored.
