### ISSUE TITLE
Error installing cargo-generate

### ISSUE THREAD

**Issue by emptytank** [cargo-generate/cargo-generate#734]
I tried to run cargo install cargo-generate via PowerShell and received an error when the compiling (see below). Any suggestions on how to resolve? Seems like the issue might be with libz-sys as other dependencies seemed to be compiling properly.

--

error: failed to run custom build command for `libz-sys v1.1.8`

Caused by:
  process didn't exit successfully: `C:\Users\_username_\AppData\Local\Temp\cargo-installm0OOVW\release\build\libz-sys-8caf2ad77f1b5009\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-env-changed=ZLIB_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=ZLIB_STATIC
  cargo:rerun-if-env-changed=ZLIB_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo-warning=Could not run `"pkg-config" "--libs" "--cflags" "zlib"`
  The pkg-config command could not be found.

  Most likely, you need to install a pkg-config package for your OS.

  If you've already installed it, ensure the pkg-config command is one of the
  directories in the PATH environment variable.

**Comment by JakubGluszek** [comment]
I also got an error trying to install cargo-generate.
❯ uname -a                                
Linux jacob-pc 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

~ 
➜ sudo cargo install cargo-generate
    Updating crates.io index
  Downloaded cargo-generate v0.16.0
  Downloaded 1 crate (86.5 KB) in 0.68s
  Installing cargo-generate v0.16.0
error: failed to compile `cargo-generate v0.16.0`, intermediate artifacts can be found at `/tmp/cargo-installB7Oht7`

Caused by:
  failed to select a version for the requirement `rhai = "^1.8"`
  candidate versions found which didn't match: 1.7.0, 1.6.1, 1.6.0, ...
  location searched: crates.io index
  required by package `cargo-generate v0.16.0`

~ took 15s 
❯

**Comment by bever1337** [comment]
I have an identical error to Jakub, but a different machine:
```
Darwin hostname.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
```

**Comment by sassman** [comment]
thanks for sharing the solution:

> Updating through `rustup` resolved the issue.
