### ISSUE TITLE
Cannot set variables from rhai hooks

### ISSUE THREAD

**Issue by tqwewe** [cargo-generate/cargo-generate#769]
I'm trying to set a variable `features` which I can use in my Cargo.toml with `{{ features }}`, but when I run cargo generate, the `{{ features }}` variable seems to be an empty string and unset.

I have setup a pre hook with `pre = ["pre-script.rhai"]`, and set the variable in there:
```js
variable::set("features", "hello");
```

**Comment by taurr** [comment]
This usecase is literally covered in the example. Unfortunately the example had another error in that it refused to use the newest `cargo generate`

**Comment by tqwewe** [comment]
I understand that it is in the example, but is the old version of `cargo generate` the reason why the variables wouldn't be working?

**Comment by taurr** [comment]
> I understand that it is in the example, but is the old version of `cargo generate` the reason why the variables wouldn't be working?

No idea, but very likely - it's been working since forever, but 1 little hickup; the timing of the hooks and what could/could not be done. That's why I added the hooks section to the book at some point. Around that time, there were some issues with variables not working proberly. The reason at the time is technical and caused by the `Liquid` API (It will silently fail assigning variables if using non-mut references). I believe it was only 1 version that was affected though.
